### ISSUE TITLE
Benchmark PFT meta-analysis

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#308]
Need to be able to check which PFTs make it through the meta-analysis without errors based on an automated scripts. When testing, also want the ability to re-run just those that are failing, so as not to waste computation time.

Need to fix the PFTs that are failing

**Comment by robkooper** [comment]
Will do a brute force run on my desktop for the next few days to see what works and what fails.

**Comment by robkooper** [comment]
Here are the results. The following PFT's are broken:
```
[id=         8 pft='tempconif' model='ED2'] : get.traits
[id=         8 pft='tempconif' model='ED2'] : BROKEN - subscript out of bounds
[id=        11 pft='shrub' model='ED2'] : get.traits
[id=        11 pft='shrub' model='ED2'] : BROKEN - Error executing db query 'select distinct variables.name from traits join variables 
[id=        19 pft='temperate.Late_Conifer' model='ED2'] : get.traits
[id=        19 pft='temperate.Late_Conifer' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=        20 pft='temperate.Southern_Pine' model='ED2'] : get.traits
[id=        20 pft='temperate.Southern_Pine' model='ED2'] : BROKEN - subscript out of bounds
[id=        21 pft='temperate.North_Mid_Hardwood' model='ED2'] : get.traits
[id=        21 pft='temperate.North_Mid_Hardwood' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=        22 pft='temperate.South_Mid_Hardwood' model='ED2'] : get.traits
[id=        22 pft='temperate.South_Mid_Hardwood' model='ED2'] : BROKEN - subscript out of bounds
[id=        39 pft='plants' model='ED2'] : get.traits
[id=        39 pft='plants' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=        51 pft='boreal.blackspruce' model='ED2'] : get.traits
[id=        51 pft='boreal.blackspruce' model='ED2'] : meta.analysis
[id=        51 pft='boreal.blackspruce' model='ED2'] : BROKEN - NOT OK!  root_respiration_rate  posterior and prior are probably not the same:
[id=        65 pft='populus' model='SIPNET'] : get.traits
[id=        65 pft='populus' model='SIPNET'] : BROKEN - duplicate 'row.names' are not allowed
[id=        70 pft='tempconif.doe_vd' model='ED2'] : get.traits
[id=        70 pft='tempconif.doe_vd' model='ED2'] : BROKEN - subscript out of bounds
[id=        83 pft='plants' model='ED2'] : get.traits
[id=        83 pft='plants' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=        95 pft='plants' model='ED2'] : get.traits
[id=        95 pft='plants' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=        99 pft='populus' model='ED2'] : get.traits
[id=        99 pft='populus' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=       104 pft='populus' model='BIOCRO'] : get.traits
[id=       104 pft='populus' model='BIOCRO'] : BROKEN - duplicate 'row.names' are not allowed
```

The following PFT's are working correctly:
```
[id=         4 pft='tempdecid' model='ED2'] : OK
[id=         5 pft='ebifarm.nfixer' model='ED2'] : OK
[id=         6 pft='ebifarm.c4grass' model='ED2'] : OK
[id=         7 pft='ebifarm.c3grass' model='ED2'] : OK
[id=         9 pft='ebifarm.forb' model='ED2'] : OK
[id=        10 pft='ebifarm.c4crop' model='ED2'] : OK
[id=        12 pft='tundra.grass' model='ED2'] : OK
[id=        13 pft='tundra.deciduous' model='ED2'] : OK
[id=        14 pft='tundra.evergreen' model='ED2'] : OK
[id=        15 pft='temperate.Late_Hardwood' model='ED2'] : OK
[id=        16 pft='temperate.Early_Hardwood' model='ED2'] : OK
[id=        17 pft='temperate.Northern_Pine' model='ED2'] : OK
[id=        18 pft='temperate.Mid_Conifer' model='ED2'] : OK
[id=        23 pft='temperate.Evergreen_Hardwood' model='ED2'] : OK
[id=        24 pft='temperate.Hydric' model='ED2'] : OK
[id=        25 pft='ebifarm.pavi' model='ED2'] : OK
[id=        26 pft='ebifarm.acru' model='ED2'] : OK
[id=        28 pft='ebifarm.acsa3' model='ED2'] : OK
[id=        30 pft='ebifarm.platanus' model='ED2'] : OK
[id=        31 pft='ebifarm.salix' model='ED2'] : OK
[id=        32 pft='ebifarm.liqui' model='ED2'] : OK
[id=        34 pft='ebifarm.quru' model='ED2'] : OK
[id=        35 pft='ebifarm.castanea' model='ED2'] : OK
[id=        37 pft='ebifarm.misp' model='ED2'] : OK
[id=        38 pft='saccharum' model='ED2'] : OK
[id=        40 pft='sugarcane-rb72454' model='ED2'] : OK
[id=        41 pft='temperate.deciduous' model='SIPNET'] : OK
[id=        42 pft='temperate.coniferous' model='SIPNET'] : OK
[id=        44 pft='gcs.corn' model='ED2'] : OK
[id=        45 pft='gcs.miscanthus' model='ED2'] : OK
[id=        46 pft='gcs.soybean' model='ED2'] : OK
[id=        47 pft='gcs.wheat' model='ED2'] : OK
[id=        49 pft='gcs.switchgrass' model='ED2'] : OK
[id=        52 pft='ebifarm.pavi.doe_vd' model='ED2'] : OK
[id=        53 pft='temperate.Late_Hardwood.doe_vd' model='ED2'] : OK
[id=        54 pft='temperate.Late_Conifer.doe_vd' model='ED2'] : OK
[id=        55 pft='temperate.Early_Hardwood.doe_vd' model='ED2'] : OK
[id=        56 pft='temperate.North_Mid_Hardwood.doe_vd' model='ED2'] : OK
[id=        57 pft='temperate.Northern_Pine.doe_vd' model='ED2'] : OK
[id=        58 pft='saof' model='BIOCRO'] : OK
[id=        59 pft='ebifarm.acsa3.doe_vd' model='ED2'] : OK
[id=        60 pft='ebifarm.prse2.doe_vd' model='ED2'] : OK
[id=        61 pft='ebifarm.quru.doe_vd' model='ED2'] : OK
[id=        62 pft='salix' model='BIOCRO'] : OK
[id=        63 pft='ebifarm.c4grass.doe_vd' model='ED2'] : OK
[id=        64 pft='ebifarm.populus' model='ED2'] : OK
[id=        67 pft='ebifarm.saof' model='ED2'] : OK
[id=        68 pft='tempdecid.doe_vd' model='ED2'] : OK
[id=        69 pft='ebifarm.salix.doe_vd' model='ED2'] : OK
[id=        72 pft='tundra.grass.doe_vd' model='ED2'] : OK
[id=        74 pft='tundra.evergreen.doe_vd' model='ED2'] : OK
[id=        75 pft='tundra.deciduous.doe_vd' model='ED2'] : OK
[id=        79 pft='temperate.Late_Hardwood.optics' model='ED2'] : OK
[id=        80 pft='temperate.Late_Conifer.optics' model='ED2'] : OK
[id=        81 pft='temperate.Early_Hardwood.optics' model='ED2'] : OK
[id=        82 pft='temperate.North_Mid_Hardwood.optics' model='ED2'] : OK
[id=        96 pft='gr.plants' model='ED2'] : OK
[id=        97 pft='agave.yield' model='ED2'] : OK
[id=        98 pft='dalec.evergreen' model='ED2'] : OK
[id=       102 pft='pavi' model='BIOCRO'] : OK
[id=       103 pft='misp' model='BIOCRO'] : OK
[id=       105 pft='temperate.Western_Pine' model='ED2'] : OK
[id=       106 pft='temperate.Western_Hardwood' model='ED2'] : OK
[id=       107 pft='temperate.Western_Fir' model='ED2'] : OK
[id=       108 pft='salix-sachalinensis' model='BIOCRO'] : OK
[id=       109 pft='salix-priors' model='BIOCRO'] : OK
[id=       110 pft='temperate.Early_Hardwood.Kent' model='ED2'] : OK
[id=       116 pft='salix-purpurea' model='BIOCRO'] : OK
[id=1000000001 pft='evergreen' model='DALEC'] : OK
```

**Comment by dlebauer** [comment]
In issue #278, the 'duplicate row names not allowed' error was caused by an incorrectly spelled pft name in the settings file.

**Comment by robkooper** [comment]
These are pulled from the pfts table in the database so all names are spelled correctly (see testpfts.R).

**Comment by dlebauer** [comment]
Did somoen (@mdietze or @robkooper?) edit the records to make these plants, plants1, plants2, etc?

**Comment by mdietze** [comment]
Yes, I did that so that PEcAn will actually run while we sort out which two need to be deleted or given more informative names. Thus far no one has claimed that they were the ones that made the Clones so I'm in favor of deleting

Also, I don't have permissions to delete PFTs on ebi-forecast. @dlebauer could you delete the PFT dalec.evergreen of type ED2

**Comment by dlebauer** [comment]
> delete the PFT dalec.evergreen of type ED2

done

**Comment by mdietze** [comment]
@robkooper where is the testpfts.R script?
Could you pull from both databases (0 and 1) and then update the list of PFTs with error? I think that code and database fixes have got a decent number of these working but I'm loosing track of which are still failing.

**Comment by robkooper** [comment]
Mike there is a new version of BETY so you might have to update your version.

**Comment by robkooper** [comment]
Right now the testpfts script is in a branch I'm working on. I'll finish it soon so I can create a pull request.

**Comment by robkooper** [comment]
This is all the broken ones left on EBI:

```
[id= 11 pft='shrub' model='ED2'] : get.traits
[id= 11 pft='shrub' model='ED2'] : BROKEN - Error executing db query 'select distinct variables.name from traits join variables 
[id= 19 pft='temperate.Late_Conifer' model='ED2'] : get.traits
[id= 19 pft='temperate.Late_Conifer' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id= 21 pft='temperate.North_Mid_Hardwood' model='ED2'] : get.traits
[id= 21 pft='temperate.North_Mid_Hardwood' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id= 22 pft='temperate.South_Mid_Hardwood' model='ED2'] : get.traits
[id= 22 pft='temperate.South_Mid_Hardwood' model='ED2'] : BROKEN - subscript out of bounds
[id= 51 pft='boreal.blackspruce' model='ED2'] : get.traits
[id= 51 pft='boreal.blackspruce' model='ED2'] : meta.analysis
[id= 51 pft='boreal.blackspruce' model='ED2'] : BROKEN - NOT OK!  root_respiration_rate  posterior and prior are probably not the same:
[id= 70 pft='tempconif.doe_vd' model='ED2'] : get.traits
[id= 70 pft='tempconif.doe_vd' model='ED2'] : BROKEN - subscript out of bounds
```

**Comment by mdietze** [comment]
@dlebauer could you delete the PFTs 'shrub' (which Pat made years ago and has no species or priors) and 'test' on ebi-forecast.

@robkooper, after David does that, could you rerun the test? I think I've got everything working now.

**Comment by dlebauer** [comment]
done

**Comment by robkooper** [comment]
Next list of broken
```
[id= 19 pft='temperate.Late_Conifer' model='ED2'] : get.traits
[id= 19 pft='temperate.Late_Conifer' model='ED2'] : BROKEN - subscript out of bounds
[id= 22 pft='temperate.South_Mid_Hardwood' model='ED2'] : get.traits
[id= 22 pft='temperate.South_Mid_Hardwood' model='ED2'] : BROKEN - subscript out of bounds
[id= 51 pft='boreal.blackspruce' model='ED2'] : get.traits
[id= 51 pft='boreal.blackspruce' model='ED2'] : meta.analysis
[id= 51 pft='boreal.blackspruce' model='ED2'] : BROKEN - NOT OK!  root_respiration_rate  posterior and prior are probably not the same:
[id= 70 pft='tempconif.doe_vd' model='ED2'] : get.traits
[id= 70 pft='tempconif.doe_vd' model='ED2'] : BROKEN - subscript out of bounds
```

**Comment by dlebauer** [comment]
@robkooper would be :8ball: :+1: if your script (or keyboard!) printed:

```sql
delete from pfts where id in (19, 22, 61, 70);
```

(easier for me to figure out what I need to do, and to do it)

**Comment by robkooper** [comment]
I'm trying to not make a decision if they should be deleted or kept around. Just showing that if I run get.traits followed by meta.analysis it does not work.

**Comment by mdietze** [comment]
Is this with the latest code? I thought for sure that my bug fixes resolved these pfts

**Comment by dlebauer** [comment]
Sorry I jumped the gun. Do I need to restore these?

**Comment by robkooper** [comment]
yeah, if possible, especially if mike's code fixes it.

**Comment by mdietze** [comment]
@dlebauer, you definitely should NOT have deleted those last few PFTs! Also, double check if you deleted 51 (on rob's list) or 61 (in your code).

**Comment by mdietze** [comment]
please let me know when the PFTs are restored so I can go back to debugging them

**Comment by mdietze** [comment]
Running on pecan2.bu.edu (where the PFTs are not deleted), I cannot replicate the error with Late_Conifer -- it builds fine for me. Haven't checked the other 3. @robkooper could you send or check in you testing script?

**Comment by dlebauer** [comment]
I've re-added all of the pfts, including both 51 and 61


```sql
INSERT INTO "pfts" ("id", "definition", "created_at", "updated_at", "name", "parent_id", "pft_type", "modeltype_id") VALUES ('51', 'Picea mariana, as typically dominates lowland sites across much of interior Alaska and Canada. Began as a clone of existing temperate.Mid_Conifer PFT.', '2011-02-01 20:32:40', '2012-10-25 00:08:56', 'boreal.blackspruce', NULL, 'plant', '1');
INSERT INTO "pfts" ("id", "definition", "created_at", "updated_at", "name", "parent_id", "pft_type", "modeltype_id") VALUES ('61', 'created by J. Mantooth for DOE variance decomposition synthesis.', '2012-11-06 16:15:33', '2012-11-06 16:15:33', 'ebifarm.quru.doe_vd', NULL, 'plant', '1');
INSERT INTO "pfts" ("id", "definition", "created_at", "updated_at", "name", "parent_id", "pft_type", "modeltype_id") VALUES ('70', 'temperate conifer. edited by SPS for DOE synthesis paper.', '2010-06-29 20:09:20', '2013-05-23 17:11:38', 'tempconif.doe_vd', NULL, 'plant', '1');
INSERT INTO "pfts" ("id", "definition", "created_at", "updated_at", "name", "parent_id", "pft_type", "modeltype_id") VALUES ('19', 'Late successional conifer (e.g. hemlock, juniper, cedar) for eastern temperate forest.  Default pft = 8.', '2011-02-01 20:35:23', '2011-02-01 20:35:23', 'temperate.Late_Conifer', NULL, 'plant', '1');
INSERT INTO "pfts" ("id", "definition", "created_at", "updated_at", "name", "parent_id", "pft_type", "modeltype_id") VALUES ('22', 'Southern half of mid-successional temperate hardwoods (e.g. oak, hickory).  No default PFT.', '2011-02-01 20:41:20', '2011-02-01 20:41:20', 'temperate.South_Mid_Hardwood', NULL, 'plant', '1');
```

**Comment by mdietze** [comment]
@dlebauer of the restored PFTs, only 51 has any species associated with it (which is the one you didn't delete originally). Please restore the pft to species table as well for the other 4 PFTs.

**Comment by robkooper** [comment]
Each of us can now run it:
```
cd pecan/tests
R CMD BATCH testpfts.R
grep '^TESTING' testpfts.R > testing.txt
```

Here is my result, right now:
```
[id=         8 pft='tempconif' model='ED2'] : get.traits
[id=         8 pft='tempconif' model='ED2'] : BROKEN - subscript out of bounds
[id=        19 pft='temperate.Late_Conifer' model='ED2'] : get.traits
[id=        19 pft='temperate.Late_Conifer' model='ED2'] : BROKEN - subscript out of bounds
[id=        20 pft='temperate.Southern_Pine' model='ED2'] : get.traits
[id=        20 pft='temperate.Southern_Pine' model='ED2'] : BROKEN - subscript out of bounds
[id=        22 pft='temperate.South_Mid_Hardwood' model='ED2'] : get.traits
[id=        22 pft='temperate.South_Mid_Hardwood' model='ED2'] : BROKEN - subscript out of bounds
[id=        51 pft='boreal.blackspruce' model='ED2'] : get.traits
[id=        51 pft='boreal.blackspruce' model='ED2'] : meta.analysis
[id=        51 pft='boreal.blackspruce' model='ED2'] : BROKEN - NOT OK!  root_respiration_rate  posterior and prior are probably not the same:
[id=        65 pft='populus' model='SIPNET'] : get.traits
[id=        65 pft='populus' model='SIPNET'] : BROKEN - duplicate 'row.names' are not allowed
[id=        70 pft='tempconif.doe_vd' model='ED2'] : get.traits
[id=        70 pft='tempconif.doe_vd' model='ED2'] : BROKEN - subscript out of bounds
[id=        99 pft='populus' model='ED2'] : get.traits
[id=        99 pft='populus' model='ED2'] : BROKEN - duplicate 'row.names' are not allowed
[id=       104 pft='populus' model='BIOCRO'] : get.traits
[id=       104 pft='populus' model='BIOCRO'] : BROKEN - duplicate 'row.names' are not allowed
```

**Comment by mdietze** [comment]
@robkooper using your script the only one of these that I can replicate is PFT 51. I just pushed from my local branch back up to github which says that my code is identical to the main line. Are you 100% sure you've pulled all my bug fixes from last week into the code you're using to run these tests?

**Comment by mdietze** [comment]
I now get OK for all PFTs
