### ISSUE TITLE
PEcAn 1.4.3 BD NARR ED failure

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#634]
The notes of the test were: 
lat/lon bug-
```
[+] Init_Met_Drivers...
==================================================
Polygon lies outside the met driver domain!!!
==================================================
+ Polygon:
- Longitude : -1.05546E+02
- Latitude : 4.00329E+01
+ File: : /home/carya/output/dbfiles/BD-b0d324f46dc
+ Meteorological data boundaries:
- West : 5.77841E+06
- East : 5.77841E+06
- South : 3.53847E+06
- North : 3.53847E+06
```

**Comment by robkooper** [comment]
Can you give me the pecan.xml, or at least the site.

**Comment by tonygardella** [comment]
The site was Niwot Ridge: US-NR1

**Comment by tonygardella** [comment]
@robkooper have you looked into this? I've been trying to find the exact run id to get the xml from this run but the date recorded on the excel doesn't match up with any runs give or take a couple days.

**Comment by bcow** [comment]
I thought this was resolved... I think the problem is that the lat lon of the NARR site will not be the same as the actual site lat lon - I'm not looking at the code right now (remind me tomorrow) but I remember fixing it for Afshin.

**Comment by robkooper** [comment]
I will have to look at this some more as well before I say fully yes it is working. I think there might have been a bug in the browndog script used.

**Comment by robkooper** [comment]
I looked at this issue and found the following (after fixing small bug)
http://pecan-dev.ncsa.illinois.edu/pecan/08-finished.php?workflowid=99000000001

This is when running Ameriflux on NIWOT using ED model and using browndog. This could be that the browndog server is still using an older version of PEcAN (1.4.5 latest release). Using a local conversion it seems like it is running correctly: 
http://pecan-dev.ncsa.illinois.edu/pecan/08-finished.php?workflowid=99000000002

**Comment by robkooper** [comment]
NARR does have issue still: http://pecan-dev.ncsa.illinois.edu/pecan/08-finished.php?workflowid=99000000003

**Comment by robkooper** [comment]
The unit stored is m, and not degrees. This is what is failing. Trying to figure out where the unit m comes from.

**Comment by mdietze** [comment]
UTM?

**Comment by robkooper** [comment]
problem i think is in the extract.nc function that tries to extract a single site from the narr data. I think the m is the meters from one of the corners of the dataset.

**Comment by robkooper** [comment]
When writing the ED_MET_DRIVER_HEADER need to make sure that lat/lon is specified as degrees and not meters. Successfull run with NARR http://pecan-dev.ncsa.illinois.edu/pecan/08-finished.php?workflowid=99000000004
